#!/usr/bin/env python3
"""
Generate CREDITS.md for the bundled codeword images.

Reads `image_attribution` from each entry in `KeebLock/Resources/codeword_data.json`
and writes a per-file attribution table to
`KeebLock/Resources/CodewordImages/CREDITS.md`. Idempotent — re-run after every
`fetch_codeword_data.py` to refresh the table.

The repo's source code is Apache-2.0, but each image retains its original
Wikimedia Commons license. Most require attribution; some additionally
require share-alike for derivative works. This file makes those licenses
visible per file so distribution is compliant.

Usage (from repo root):
    python3 scripts/build_credits.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "KeebLock" / "Resources" / "codeword_data.json"
OUTPUT = REPO_ROOT / "KeebLock" / "Resources" / "CodewordImages" / "CREDITS.md"


def md_link(text: str | None, url: str | None) -> str:
    """Markdown link, with pipe-escaping for table cells."""
    label = (text or "").strip()
    if not label and not url:
        return "—"
    if not url:
        return label.replace("|", "\\|") or "—"
    if not label:
        label = url
    return f"[{label.replace('|', '\\|')}]({url})"


def main() -> int:
    if not MANIFEST.exists():
        print(f"error: manifest not found at {MANIFEST}", file=sys.stderr)
        return 1

    manifest = json.loads(MANIFEST.read_text())
    data = manifest.get("data", {})

    rows: list[dict] = []
    missing: list[str] = []
    licenses: Counter[str] = Counter()
    sa_required = 0  # share-alike → public-repo distribution must include this notice

    for word in sorted(data):
        entry = data[word]
        attr = entry.get("image_attribution")
        filename = entry.get("image_filename") or f"{word}.jpg"
        if not attr:
            missing.append(word)
            continue

        license_name = attr.get("license_name") or "unknown"
        licenses[license_name] += 1
        if "sa" in (attr.get("license_spdx") or "").lower():
            sa_required += 1

        # commons_file_title comes back as "File:Foo bar.jpg" — drop the prefix
        # for the table label, but keep the underlying page URL intact.
        title = (attr.get("commons_file_title") or "").removeprefix("File:")

        rows.append({
            "filename":     filename,
            "title":        title,
            "page_url":     attr.get("commons_page_url"),
            "author":       attr.get("author") or attr.get("uploader"),
            "author_url":   attr.get("author_url"),
            "license_name": license_name,
            "license_url":  attr.get("license_url"),
        })

    # ---- Render -------------------------------------------------------------
    lines: list[str] = []
    lines.append("# Codeword Image Credits")
    lines.append("")
    lines.append(
        f"The {len(data)} images in this directory are sourced from "
        "[Wikimedia Commons](https://commons.wikimedia.org/). "
        "KeebLock's source code is Apache-2.0, but **each image retains its "
        "original Wikimedia license**. Most require attribution; "
        f"{sa_required} require share-alike for derivative works."
    )
    lines.append("")
    lines.append(
        "_This file is generated by `scripts/build_credits.py` from "
        "`KeebLock/Resources/codeword_data.json`. Do not edit by hand — "
        "re-run the script after fetching new images._"
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **{len(rows)}** images with recorded attribution")
    if missing:
        lines.append(
            f"- **{len(missing)}** images missing attribution (needs review): "
            f"{', '.join(f'`{w}`' for w in missing)}"
        )
    for lic, count in licenses.most_common():
        lines.append(f"- **{count}** × {lic}")
    lines.append("")
    lines.append("## Per-file attribution")
    lines.append("")
    lines.append("| File | Source page | Author | License |")
    lines.append("|------|-------------|--------|---------|")
    for row in rows:
        file_cell    = f"`{row['filename']}`"
        title_cell   = md_link(row["title"], row["page_url"])
        author_cell  = md_link(row["author"], row["author_url"])
        license_cell = md_link(row["license_name"], row["license_url"])
        lines.append(f"| {file_cell} | {title_cell} | {author_cell} | {license_cell} |")
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))

    rel = OUTPUT.relative_to(REPO_ROOT)
    print(f"Wrote {rel} ({len(rows)} entries, {len(missing)} missing)")
    if missing:
        print(f"  Missing: {', '.join(missing)}")
    print(f"  License mix:")
    for lic, count in licenses.most_common():
        print(f"    {count:3d}  {lic}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
